# Generated by Django 4.0 on 2021-12-18 03:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=747),
            preserve_default=False,
        ),
    ]
