# Generated by Django 3.2.12 on 2022-02-17 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_reservation_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlotMeetingData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meet_data', models.JSONField()),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.timeslot')),
            ],
        ),
    ]
