# Generated by Django 3.2.12 on 2022-02-17 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_timeslotmeetingdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeSlotMeetingData',
            new_name='ScheduleMeetingData',
        ),
        migrations.AlterField(
            model_name='schedulemeetingdata',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.schedule'),
        ),
    ]
