# Generated by Django 3.2.12 on 2022-02-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_timeslot_schedulemeetingdata_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='calendar_id',
            field=models.CharField(default='frigg', max_length=1024),
            preserve_default=False,
        ),
    ]
