# Generated by Django 3.2.12 on 2022-02-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_schedule_calendar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='calendar_meet_data',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ScheduleMeetingData',
        ),
    ]
