# Generated by Django 3.2.12 on 2022-04-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_schedulesubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulesubscription',
            name='add_as_guest',
            field=models.BooleanField(default=False),
        ),
    ]
