# Generated by Django 3.2.12 on 2022-04-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_schedulesubscription_add_as_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='visibility',
            field=models.CharField(choices=[('A', 'Public'), ('U', 'Unlisted'), ('P', 'Private')], default='A', max_length=1),
        ),
    ]
