# Generated by Django 3.2.12 on 2022-04-05 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_schedule_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='id',
            new_name='uuid',
        ),
    ]
