# Generated by Django 3.2.13 on 2022-05-05 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_historicalreservation_historicalschedule_historicalschedulesubscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalSchedule',
        ),
    ]
