# Generated by Django 4.1.7 on 2023-05-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_historicalreservation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
